server {
    server_tokens off;
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location /api/ {
        proxy_pass http://api-service:8000;
    }

    location @backend {
        proxy_pass http://api-service:8000;
    }
}